# Generated by Django 5.1 on 2024-08-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroomtask',
            old_name='student',
            new_name='classroom',
        ),
    ]
