# Generated by Django 5.1 on 2024-08-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_manager', '0002_rename_student_classroomtask_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='gpa',
            field=models.FloatField(default=None),
        ),
    ]
