# Generated by Django 5.1 on 2024-09-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_manager', '0003_submission_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionfile',
            name='fileName',
        ),
        migrations.RemoveField(
            model_name='submissionfile',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='taskfile',
            name='fileName',
        ),
        migrations.RemoveField(
            model_name='taskfile',
            name='filePath',
        ),
        migrations.AddField(
            model_name='classroomtask',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(null=True, upload_to='submissions'),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='file',
            field=models.FileField(null=True, upload_to='tasks'),
        ),
    ]
