# Generated by Django 5.1 on 2024-09-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_manager', '0004_remove_submissionfile_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomtask',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='classroomtask',
            name='isAssignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='gpa',
            field=models.FloatField(null=True),
        ),
    ]
